# Generated by Django 3.0.6 on 2020-06-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbagecollector', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='image_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
