# Generated by Django 3.0.6 on 2020-07-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbagecollector', '0006_cleanup_level_trashcleanup_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lavel',
            new_name='level',
        ),
    ]
