# Generated by Django 3.0.6 on 2020-08-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbagecollector', '0009_userorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanup',
            name='latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cleanup',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
