# Generated by Django 3.0.6 on 2020-08-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbagecollector', '0010_auto_20200828_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='icon_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
